### ISSUE TITLE
Customize image console log

### ISSUE THREAD

**Issue by YanzhongSu** [GoogleCloudPlatform/dataproc-custom-images#29]
I want to see the **log** of customization-script while creating custom image using generate_custom_image.py . Does anyone know how to do that?  Right now when I tried to create custom image, it throws me the following error. I do not know what went wrong. The customization-script seems to be working fine when executed in a separate VM.

```
[Daisy] Errors in one or more workflows:
  conda-spark-pip-version: step "wait-for-inst-install" run error: WaitForInstancesSignal FailureMatch found for "conda-spark-pip-version-install-conda-spark-pip-version-vgz0v": "BuildFailed: Dataproc Initialization Actions Failed. Please check your initialization script."
Traceback (most recent call last):
  File "dataproc/cloud-dataproc/custom-images/generate_custom_image.py", line 429, in <module>
    run()
  File "dataproc/cloud-dataproc/custom-images/generate_custom_image.py", line 420, in run
    daisy_image_creator.create(args)
  File "/Users/Documents/copofi/gitlab/core-spark/dataproc/cloud-dataproc/custom-images/daisy_image_creator.py", line 43, in create
    os.path.abspath(args.daisy_path), workflow_script)
  File "/Users/Documents/copofi/gitlab/core-spark/dataproc/cloud-dataproc/custom-images/daisy_workflow_executor.py", line 42, in run
    raise RuntimeError("Error building custom image.")
RuntimeError: Error building custom image.
```

The customization-script is as follows:
```
#!/bin/bash
conda install --yes python=3.6.7 numpy=1.15.4
conda install --yes python=3.6.7 pandas=0.23.4
conda install --yes python=3.6.7 ujson=1.35
conda install --yes python=3.6.7 geopandas=0.4.0
conda install --yes python=3.6.7 lxml=4.3.0
```

**Comment by medb** [comment]
It's displayed now:
```
Oct 17 21:42:08 test-01-install startup-script: INFO startup-script: Copying gs://test-bucket/dataproc-custom-image-01/custom-image-test-01-20191017-144146/sources/init_actions.sh...
Oct 17 21:42:08 test-01-install startup-script: INFO startup-script: Operation completed over 2 objects/3.0 KiB.
Oct 17 21:42:08 test-01-install startup-script: INFO startup-script: + bash -x ./init_actions.sh
Oct 17 21:42:08 test-01-install startup-script: INFO startup-script: + apt-get install python-pip
Oct 17 21:42:09 test-01-install startup-script: INFO startup-script: Reading package lists...
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script: Building dependency tree...
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script: Reading state information...
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script: The following additional packages will be installed:
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-all-dev python-cffi-backend python-crypto python-cryptography
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-dbus python-dev python-enum34 python-gi python-idna python-ipaddress
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-keyring python-keyrings.alt python-pip-whl python-pyasn1
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-secretstorage python-wheel python-xdg python2.7-dev
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script: Suggested packages:
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-crypto-dbg python-crypto-doc python-cryptography-doc
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-cryptography-vectors python-dbus-dbg python-dbus-doc
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-enum34-doc python-gi-cairo gnome-keyring libkf5wallet-bin
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   gir1.2-gnomekeyring-1.0 python-fs python-gdata python-kde4 python-keyczar
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   doc-base python-secretstorage-doc
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script: The following NEW packages will be installed:
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all
Oct 17 21:42:10 test-01-install startup-script: INFO startup-script:   python-all-dev python-cffi-backend python-crypto python-cryptography
```
